package eu.cloud4soa.c4sgitservice.dao;


import java.util.List;

import eu.cloud4soa.c4sgitservice.datamodel.User;
import org.springframework.data.domain.Pageable;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.stereotype.Repository;

/**
 * Created with IntelliJ IDEA.
 * User: pgouvas
 * Date: 8/2/12
 * Time: 12:30 PM
 */
public interface UserRepository extends JpaRepository<User,Long>{
    
    /*
     * Will produce autogenerated DAO Impl
     */
    public User findByUserId(Long userid);

    public List<User> findByUsername(String username);

    public List<User> findByUsernameAndPassword(String username,String password);

    //public List<User> findByUserIdLike(String userid);
    
    //@Query("select count (*) from USERS u where u.userId like ?1 ")
    //public long countByUserIdLike(String userid);
            
    //public List<User> findByUserIdLike(String userid,Pageable page);
        
    //public User findByUserIdAndDorCode(String userid,Long dorcode);
    
}